services:
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    environment:
      - CONTAINERS=1  # Allow access to viewing containers
      - SERVICES=0    # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0       # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0        # Disallow any POST operations (effectively read-only)
    volumes:
      - type: bind # (optional) For docker integrations
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - docker-services
    ports:
      - 127.0.0.1:2375:2375
    restart: unless-stopped

# Create a new network for the services to communicate over
#
# $ docker network create \
#   --driver bridge \
#   --subnet 172.100.0.0/16 \
#   --gateway 172.100.0.1 \
#   --opt "com.docker.network.bridge.enable_icc"="true" \
#   --opt "com.docker.network.bridge.enable_ip_masquerade"="true" \
#   --opt "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" \
#   --opt "com.docker.network.driver.mtu"="1500" \
#   docker-services

networks:
  docker-services:
    external: true