services:
  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    environment:
      - CONTAINERS=1  # Allow access to viewing containers
      - SERVICES=0    # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0       # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0        # Disallow any POST operations (effectively read-only)
    volumes:
      - type: bind # (optional) For docker integrations
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - traefik
    ports:
      - 127.0.0.1:2375:2375

networks:
  traefik:
    external: true
