services:
  controller:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: ${COMPOSE_PROJECT_NAME}_controller
    depends_on:
      - db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
      - MEM_LIMIT=default #optional
      - MEM_STARTUP=default #optional
      - MONGO_TLS= #optional
    volumes:
      - type: volume
        source: config
        target: /config
        read_only: false
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    networks:
      - docker-services
    restart: unless-stopped

  db:
    image: docker.io/mongo:8.0.4
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - type: volume
        source: mongo_db
        target: /data/db
        read_only: false
      - type: volume
        source: mongo_db_config
        target: /data/configdb
        read_only: false
      - /root/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      - docker-services
    restart: unless-stopped

  logs:
    image: bash
    container_name: ${COMPOSE_PROJECT_NAME}_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /config/logs/*.log'
    volumes:
      - type: volume
        source: config
        target: /config
        read_only: true
    networks:
      - docker-services
    restart: unless-stopped

volumes:
  config:
  mongo_db:
  mongo_db_config:

# Create a new network for the services to communicate over
#
# $ docker network create \
#   --driver bridge \
#   --subnet 172.100.0.0/16 \
#   --gateway 172.100.0.1 \
#   --opt "com.docker.network.bridge.enable_icc"="true" \
#   --opt "com.docker.network.bridge.enable_ip_masquerade"="true" \
#   --opt "com.docker.network.bridge.host_binding_ipv4"="0.0.0.0" \
#   --opt "com.docker.network.driver.mtu"="1500" \
#   docker-services

networks:
  docker-services:
    external: true